apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kubernetes-external-secrets
  name: kubernetes-external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubernetes-external-secrets
  template:
    metadata:
      labels:
        name: kubernetes-external-secrets
        service: kubernetes-external-secrets
    spec:
      serviceAccountName: kubernetes-external-secrets-service-account
      containers:
        image: "godaddy/kubernetes-external-secrets"
        imagePullPolicy: Always
        name: kubernetes-external-secrets
