apiVersion: v1
name: kubernetes-external-secrets
version: 5.1.0
appVersion: 5.1.0
description: Kubernetes External Secrets CustomResourceDefinition
keywords:
  - kubernetes-external-secrets
  - secrets
home: https://github.com/godaddy/kubernetes-external-secrets
sources:
  - https://github.com/godaddy/kubernetes-external-secrets
maintainers:
  - name: jeffpearce
    email: jxpearce@godaddy.com
  - name: keweilu
    email: klu6@godaddy.com
